PREFIX xhv: <http://www.w3.org/1999/xhtml/vocab#>
PREFIX cc: <http://creativecommons.org/ns#>
PREFIX rdfatest: <http://rdfa.info/vocabs/rdfa-test#>
ASK WHERE {
  <$TCPATH/0114.xhtml>
    xhv:index <http://rdfa.info/test-suite/#>;
    xhv:next <$TCPATH/0115.xhtml>;
    xhv:up <$TCPATH/>;
    cc:attributionURL <http://rdfa.info/>;
    rdfatest:cornerCase1 <$TCPATH/>;
    rdfatest:cornerCase3 <$TCPATH/...>;
    rdfatest:cornerCase4 <$TCPATH/0114.xhtml?foo=bar../baz>;
    rdfatest:cornerCase5 <http://rdfa.info/test-suite/test-cases/.../.htaccess>.
}
