ASK WHERE {
	<http://rdfa.digitalbazaar.com/test-suite/test-cases/0114.xhtml> <http://www.w3.org/1999/xhtml/vocab#up> <http://rdfa.digitalbazaar.com/test-suite/xhtml-manifest.rdf> .
	<http://rdfa.digitalbazaar.com/test-suite/test-cases/0114.xhtml> <http://www.w3.org/1999/xhtml/vocab#prev> <http://rdfa.digitalbazaar.com/test-suite/test-cases/0113.xhtml> .
	<http://rdfa.digitalbazaar.com/test-suite/test-cases/0114.xhtml> <http://creativecommons.org/ns#attributionURL> <http://rdfa.digitalbazaar.com/> .
}