ASK WHERE {
<$TCPATH/0115.xhtml>
   <http://www.example.com/entity>
      "<string>" .
<$TCPATH/0115.xhtml>
   <http://www.example.com/entity>
      "Ben & Co." .
<$TCPATH/0115.xhtml>
   <http://www.example.com/entity>
      "@" .
<$TCPATH/0115.xhtml>
   <http://www.example.com/entity>
      "@" .
}
