ASK WHERE {
    <$TCPATH/0310.xhtml#therole> <http://www.w3.org/1999/xhtml/vocab#role> <http://www.example.com/roles/somerole>
    <$TCPATH/0310.xhtml#therole> <http://www.w3.org/1999/xhtml/vocab#role> <http://www.w3.org/1999/xhtml/vocab#someOtherRole>
    <$TCPATH/0310.xhtml#therole> <http://www.w3.org/1999/xhtml/vocab#role> <http://www.example.com/alternate/role>
}
